# Generated by Django 5.1.15 on 2026-08-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qrsession',
            name='status',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('EXPIRED', 'Expired')], default='REGISTER', max_length=10),
        ),
    ]
