# Generated by Django 5.1.15 on 2026-08-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_system', '0002_qrsession_expires_at_alter_qrsession_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrsession',
            name='status',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='REGISTER', max_length=10),
        ),
    ]
